spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysqladmin

  redis:
    host: 192.168.211.139

  jpa:
    show-sql: true

  rabbitmq:
    host: 192.168.211.139
